// This file is auto-generated by scripts/generatePhotoList.js
// Do not edit manually!

export const photoUrls = [
    "/photos/Snapchat-141989587.jpg",
    "/photos/Snapchat-2086634025.jpg",
    "/photos/Snapchat-304458227.jpg",
    "/photos/Snapchat-331650165.jpg"
];
